language: node_js
node_js:
  - "10"
addons: code_climate
env:
  global:
    - CC_TEST_REPORTER_ID=2cd06bda2b204d3f803037416a8b53c0b11ae3c9dd3cf18e511635d047b90c52
cache:
  directories:
    - node_modules
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - yarn test --detectOpenHandles
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
